### ISSUE TITLE
mkdir permission denied.

### ISSUE THREAD

**Issue by uscoders82** [HellRok/Taylor#10]
I just installed Taylor on Windows 10, but when i try to run `taylor new` it returns the following error:
```
 [6] (unknown):0
        [5] (unknown):0:in call
        [4] (unknown):0:in new
        [3] (unknown):0:in initialize
        [2] (unknown):0:in call
        [1] (unknown):0:in create_directory!
(unknown):0:in mkdir: Permission denied - taylor_game (Errno::EACCES)
```
Is there something I did wrong, and if so how do I get it to work.

**Comment by HellRok** [comment]
Hi!

I can't reproduce this on my Windows 10 machine, at least not without more information.

1. What directory are you running `taylor new` in?
2.  Are you sure you have permission to change files/folders in that directory?
3. Can you try and run `taylor new` on your desktop? (Hold shift and right click your desktop, then click "Open power shell here", then run `taylor new`)

This may be of help https://support.microsoft.com/en-us/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e

**Comment by uscoders82** [comment]
The issue ended up magically resolving itself, and I dont know how! Thanks for the help anyway.
