### ISSUE TITLE
Advocate the Web functionality

### ISSUE THREAD

**Issue by westonganger** [HellRok/Taylor#12]
The web functionality of this library is one of its biggest selling features however its hardly mentioned

On Reddit I am starting to see the taylor name come up more and more often. It would be huge to have the web/wasm support be marketed.

Other competitors status in the ruby/web/wasm space:
- Dragon Ruby (closed source, web/wasm support with mruby)
- Ruby2D (no web/wasm support with mruby, existing PR in draft for too long/stalled)
- Gosu (no web/wasm support)

If we advocate for Taylor Web/WASM support than that puts Taylor at the top of the pile, being that its both open source and has web/wasm support with mruby.

### Suggested actions

1. Mention web/wasm (and other platforms) near top of taylor Github readme.

2. Mention web/wasm on taylor home page, https://taylor.oequacki.com/
<img width="1057" alt="Screenshot 2023-03-09 at 9 35 42 AM" src="https://user-images.githubusercontent.com/3414795/224110067-157f5e6d-22ec-4bc5-bb0d-6aa091bd3249.png">

3. Mention web/wasm here on taylor getting started page, https://taylor.oequacki.com/documentation/tutorials/getting_started/
<img width="380" alt="Screenshot 2023-03-09 at 9 39 58 AM" src="https://user-images.githubusercontent.com/3414795/224110470-1979a696-69a8-4de2-834c-f01657139f08.png">

4. Add web/browser section on the cheatsheet, https://taylor.oequacki.com/documentation/tutorials/cheat_sheet/

**Comment by HellRok** [comment]
Thanks for another issue raised!

I've now added platform support towards the top of the Taylor website
![image](https://user-images.githubusercontent.com/6147202/224975747-d92bab09-5da6-4e4c-8bee-bfb843d54a84.png)

and I have also updated the Cheat Sheet and Getting Started pages, although I wasn't really sure what to add to the Getting Started page I did notice some weird grammar towards the end that I have updated.
