### ISSUE TITLE
Platformer and Gestures examples in Taylor Playground won't run

### ISSUE THREAD

**Issue by Chadowo** [HellRok/Taylor#13]
As the title says, The platformer and Gestures example can't run on the playground, I'm using Firefox 111 on linux, taking a look on the dev console reveals this error
`Uncaught (in promise) Please compile your program with async support in order to use asynchronous operations like emscripten_sleep`

After looking on the source code for the platformer example it seemed like there was a chunk of code missing required for running in web as stated in the [cheatsheet](https://taylor.oequacki.com/documentation/tutorials/cheat_sheet/#web), so I did the next changes to the platformer source code

```ruby
# Was until window_should_close?
def main
  # do game stuff...
end

# Added this before close_window
if browser?
  set_main_loop 'main'
end
```

doing that, however gave me this error
`Uncaught Infinity Taylor Playground.js:225:3`
I'm not sure if I'm missing something or not, help is sure appreciated!

**Comment by HellRok** [comment]
Thank you for bringing this to my attention, I apparently missed updating these when I was doing a migration away from ASYNCIFY in emscripten. I have tested all the examples and confirmed they now all work.
