### ISSUE TITLE
require/file io

### ISSUE THREAD

**Issue by Salvakiya** [HellRok/Taylor#14]
Does this support any additional functionality over mruby such as require, load, or file io operations?

specifically things like this fork of mruby does? https://github.com/iij/mruby

has some really good features.

**Comment by HellRok** [comment]
It does indeed! The full list of mgems I include are:

- mruby-exit
- mruby-sleep
- iij/mruby-dir
- iij/mruby-env
- iij/mruby-iijson
- iij/mruby-mtest
- hellrok/mruby-regexp-pcre
- katzer/mruby-tiny-opt-parser
- Asmod4n/mruby-uri-parser
- matsumotory/mruby-simplehttp
- matsumotory/mruby-simplehttpserver
- mattn/mruby-base64
- mattn/mruby-require

You can see this in the ]mruby build configs](https://github.com/HellRok/Taylor/blob/main/scripts/mruby/linux.rb) I use.

**Comment by Salvakiya** [comment]
Thanks! Glad to hear it!

I am looking into Taylor as a possible open source replacement to DragonRuby.

Cheers!
