### ISSUE TITLE
Make the github URL known

### ISSUE THREAD

**Issue by rubyFeedback** [HellRok/Taylor#2]
I found the project via reddit.

The github project I found from the URL for the downloads.

It would be nice if you could add this on the homepage somehow, so people can
report issues and so forth.

**Comment by HellRok** [comment]
The GitHub link is at the top of http://taylor.oequacki.com/, I could try adding it to the footer or maybe even a "Report bugs here" type link. I'll look into this.

**Comment by HellRok** [comment]
I've now added a footer and a direct link to GitHub in the downloads list
