### ISSUE TITLE
Website: Full documentation link in the cheatsheet gives an 403 error

### ISSUE THREAD

**Issue by Chadowo** [HellRok/Taylor#20]
![img](https://github.com/HellRok/Taylor/assets/83732118/0bee99b9-aff6-48fb-b61d-a34a1d23858e)

The troublesome link("here" on the attached image) points to https://www.taylormadetech.dev/documentation/taylor/ 
however, the link in the README does work: https://www.taylormadetech.dev/documentation/taylor/latest/

I see that at the time of this issue you're updating all links to your new domain, so I hope I'm not being too dense if you've already thought of updating that link but still didn't for a lack of time.

**Comment by HellRok** [comment]
Thank you for pointing this out, it turns out this link has been broken for a long time and I didn't notice! This was just an oversight on my part when I updated the documentation to contain all versions and not a lack of time.
