### ISSUE TITLE
Typo In README

### ISSUE THREAD

**Issue by Chadowo** [HellRok/Taylor#23]
In the 5th step of the "Compile Yourself" section.
> 5. Take make it easier to run, you can create a `taylor-dev` script and populate
> it with:
> ```shell
> #!/usr/bin/env bash
> TAYLOR_PATH=/home/sean/code/taylor/
>
> "$TAYLOR_PATH/dist/linux/debug/taylor" "$TAYLOR_PATH/cli-tool/cli.rb" "$@"
> ```

It should read "**To** make it easier to run [...]" shouldn't it?

**Comment by HellRok** [comment]
Thanks for the heads up, this has now been fixed.
