### ISSUE TITLE
More standalone / small-ish examples

### ISSUE THREAD

**Issue by rubyFeedback** [HellRok/Taylor#3]
Would it be possible to, say, add examples/ or something and add standalone examples there?

I learn best from adapting existing code. I used this for ruby-gtk and gosu for instance.

When I invest time into a new GUI toolkit I try to see what is all possible, so it would help to
see how things could be added (e. g. "how would I add a button-like user element" aka 
on mouse click event do something, how to change font, colours and so on).

These examples can be very short, really mostly just focus on one aspect. And a few
more complex examples at a later point. I'll definitely check out taylor in the future; am
just a bit scared about the time investment without knowing that this may be useful. :)

(While I know ruby, C is unfortunately above my head, so I try to stay "within" ruby at
all times.)

**Comment by HellRok** [comment]
There are some examples and I have now linked them from the README, they'll slowly grow as I port more stuff and build more games. I'm hoping to make something that is a decent showcase of the system and not a rushed game jam entry.

If you're curious you can checkout my only complete "game" over here https://hellrok.itch.io/mini-jam-88-rush
