### ISSUE TITLE
Additive Blending

### ISSUE THREAD

**Issue by distantforest1** [HellRok/Taylor#32]
Hi I'm coming from another raylib project where I can set the blending to achieve some nice lighting effects:
![blending](https://github.com/user-attachments/assets/d7163c13-9011-4164-a2d5-7b4fa58e7c27)
using things like `rl.BeginBlendMode(rl.BLEND_ADDITIVE)` and `rl.EndBlendMode`. However I cant seem to find it in Taylor. How would I achieve this?
btw Ruby + Raylib seems pretty fun so far.

**Comment by HellRok** [comment]
Hi,

I haven't yet implemented this function but will be doing so once I've finished my refactor work.

Thanks for taking an interest in Taylor!

Cheers,
Sean
