### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by rubyFeedback** [HellRok/Taylor#4]
I just did a git clone checkout and compiled it. It compiled without errors:

 ./vendor/linux/raylib/include/ build/linux/debug/argv.o build/linux/debug/main.o build/linux/debug/mruby_integration/audio.o build/linux/debug/mruby_integration/audio/device.o build/linux/debug/mruby_integration/audio/music.o build/linux/debug/mruby_integration/audio/sound.o build/linux/debug/mruby_integration/core.o build/linux/debug/mruby_integration/core/cursor.o build/linux/debug/mruby_integration/core/drawing.o build/linux/debug/mruby_integration/core/files.o build/linux/debug/mruby_integration/core/gestures.o build/linux/debug/mruby_integration/core/input.o build/linux/debug/mruby_integration/core/input/gamepad.o build/linux/debug/mruby_integration/core/input/keyboard.o build/linux/debug/mruby_integration/core/input/mouse.o build/linux/debug/mruby_integration/core/input/touch.o build/linux/debug/mruby_integration/core/misc.o build/linux/debug/mruby_integration/core/screen_space.o build/linux/debug/mruby_integration/core/timing.o build/linux/debug/mruby_integration/core/window.o build/linux/debug/mruby_integration/models/camera2d.o build/linux/debug/mruby_integration/models/colour.o build/linux/debug/mruby_integration/models/font.o build/linux/debug/mruby_integration/models/image.o build/linux/debug/mruby_integration/models/music.o build/linux/debug/mruby_integration/models/rectangle.o build/linux/debug/mruby_integration/models/sound.o build/linux/debug/mruby_integration/models/texture2d.o build/linux/debug/mruby_integration/models/vector2.o build/linux/debug/mruby_integration/shapes.o build/linux/debug/mruby_integration/shapes/circle.o build/linux/debug/mruby_integration/shapes/collision.o build/linux/debug/mruby_integration/shapes/ellipse.o build/linux/debug/mruby_integration/shapes/line.o build/linux/debug/mruby_integration/shapes/pixel.o build/linux/debug/mruby_integration/shapes/rectangle.o build/linux/debug/mruby_integration/shapes/ring.o build/linux/debug/mruby_integration/shapes/triangle.o build/linux/debug/mruby_integration/struct_types.o build/linux/debug/mruby_integration/structs.o build/linux/debug/mruby_integration/text.o build/linux/debug/mruby_integration/textures.o build/linux/debug/raygui.o ./vendor/linux/libmruby.a ./vendor/linux/raylib/lib/libraylib.a -l dl -l pthread

However had, I don't quite know what to do next now ... could you perhaps add a bit more content to the main README? Perhaps "next steps" or so? Or the omnipresent "hello world" example after having compiled/installed taylor? Right now I am not sure which way to go next from here ...

**Comment by HellRok** [comment]
I have now added some basic instructions on how to get Taylor built and running locally to the README
