### ISSUE TITLE
Intel Mac issues?

### ISSUE THREAD

**Issue by epugh** [HellRok/Taylor#8]
Just tried out the new release on a older OSX laptop with Intel chip:

```
(base) ➜  Downloads ./taylor --version
zsh: bad CPU type in executable: ./taylor
```

**Comment by HellRok** [comment]
Hi,

Could you please run `file taylor` and give me the output? Also which model of OSX laptop are you running?

I did bump the minimum required SDK to get support for M1 macs which will have also effected the Intel build

**Comment by epugh** [comment]
```
(base) ➜  Downloads file taylor
taylor: Mach-O 64-bit executable arm64
```

I have a MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) running Catalina 10.15.7...

I'm realizing that I am a few OS's behind, and so a fair response would be to update to a newer one!

**Comment by HellRok** [comment]
It looks like you've downloaded the Apple architecture version, not the Intel version, try downloading this and see how you go https://github.com/HellRok/Taylor/releases/download/v0.3.12/taylor-osx-intel-v0.3.12.zip

**Comment by epugh** [comment]
Doh!  That was it!  Thanks!

**Comment by HellRok** [comment]
You're more than welcome
