### ISSUE TITLE
Documentation for taylor-config.json / Web support

### ISSUE THREAD

**Issue by westonganger** [HellRok/Taylor#9]
Is there any documentation for taylor-config.json, as seen in the playground, https://github.com/HellRok/TaylorPlayground/blob/main/taylor-config.json

In particular I was interested in the web support that is provided. Would like some more details about it works.

**Comment by HellRok** [comment]
Hi!

I've now created some documentation around the `taylor_config.json` file, you can find it here https://taylor.oequacki.com/documentation/taylor/latest/file.taylor_config.json.html

Let me know if there's anything more you want to know.

Cheers,
Sean
